---
users:

  'plone':
    name: 'Plone installation'
    email: 'gitec.interlegis@gmail.com'
    public_keys: []
    state: present
    shell: '/bin/bash'
    groups:
      - 'docker'
      - 'plone'
